[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow = "Hr1ebtraa2NChqt3coBK6jJCVEyCjP6QcQSH56HuFR6S"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
